# Generated by Django 5.2.1 on 2025-06-09 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MentorRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits without country code', regex='^\\d{10}$')])),
                ('stakeholder_types', models.JSONField(default=list)),
                ('other_stakeholder_type', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(choices=[('andhra_pradesh', 'Andhra Pradesh'), ('arunachal_pradesh', 'Arunachal Pradesh'), ('assam', 'Assam'), ('bihar', 'Bihar'), ('chhattisgarh', 'Chhattisgarh'), ('goa', 'Goa'), ('gujarat', 'Gujarat'), ('haryana', 'Haryana'), ('himachal_pradesh', 'Himachal Pradesh'), ('jharkhand', 'Jharkhand'), ('karnataka', 'Karnataka'), ('kerala', 'Kerala'), ('madhya_pradesh', 'Madhya Pradesh'), ('maharashtra', 'Maharashtra'), ('manipur', 'Manipur'), ('meghalaya', 'Meghalaya'), ('mizoram', 'Mizoram'), ('nagaland', 'Nagaland'), ('odisha', 'Odisha'), ('punjab', 'Punjab'), ('rajasthan', 'Rajasthan'), ('sikkim', 'Sikkim'), ('tamil_nadu', 'Tamil Nadu'), ('telangana', 'Telangana'), ('tripura', 'Tripura'), ('uttar_pradesh', 'Uttar Pradesh'), ('uttarakhand', 'Uttarakhand'), ('west_bengal', 'West Bengal'), ('andaman_nicobar', 'Andaman and Nicobar Islands'), ('chandigarh', 'Chandigarh'), ('dadra_nagar_haveli', 'Dadra and Nagar Haveli and Daman and Diu'), ('delhi', 'Delhi'), ('jammu_kashmir', 'Jammu and Kashmir'), ('ladakh', 'Ladakh'), ('lakshadweep', 'Lakshadweep'), ('puducherry', 'Puducherry')], max_length=50)),
                ('organization_name', models.CharField(max_length=255)),
                ('association_interest', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe'), ('already_associated', 'Already Associated with Eureka! 2024')], max_length=20)),
                ('linkedin_url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('networking_cities', models.JSONField(default=list)),
                ('other_networking_city', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_sector_1', models.CharField(choices=[('blockchain', 'Blockchain / Deep Learning / Web3'), ('fmcg', 'FMCG'), ('saas', 'SaaS'), ('foodtech', 'FoodTech'), ('edutech', 'EduTech'), ('fintech', 'FinTech'), ('biotech', 'BioTech'), ('ecommerce', 'E-Commerce'), ('healthcare', 'Healthcare'), ('consulting', 'Consulting'), ('agriculture', 'Agriculture'), ('iot', 'IoT'), ('manufacturing', 'Manufacturing'), ('greentech', 'GreenTech and Renewable Technology'), ('it', 'IT'), ('wearable', 'Wearable Tech'), ('chemical', 'Chemical'), ('bigdata', 'Big Data and Analysis'), ('social', 'Social Startups'), ('logistics', 'Logistics & Supply Chain')], max_length=20)),
                ('preferred_sector_2', models.CharField(choices=[('blockchain', 'Blockchain / Deep Learning / Web3'), ('fmcg', 'FMCG'), ('saas', 'SaaS'), ('foodtech', 'FoodTech'), ('edutech', 'EduTech'), ('fintech', 'FinTech'), ('biotech', 'BioTech'), ('ecommerce', 'E-Commerce'), ('healthcare', 'Healthcare'), ('consulting', 'Consulting'), ('agriculture', 'Agriculture'), ('iot', 'IoT'), ('manufacturing', 'Manufacturing'), ('greentech', 'GreenTech and Renewable Technology'), ('it', 'IT'), ('wearable', 'Wearable Tech'), ('chemical', 'Chemical'), ('bigdata', 'Big Data and Analysis'), ('social', 'Social Startups'), ('logistics', 'Logistics & Supply Chain')], max_length=20)),
                ('preferred_sector_3', models.CharField(choices=[('blockchain', 'Blockchain / Deep Learning / Web3'), ('fmcg', 'FMCG'), ('saas', 'SaaS'), ('foodtech', 'FoodTech'), ('edutech', 'EduTech'), ('fintech', 'FinTech'), ('biotech', 'BioTech'), ('ecommerce', 'E-Commerce'), ('healthcare', 'Healthcare'), ('consulting', 'Consulting'), ('agriculture', 'Agriculture'), ('iot', 'IoT'), ('manufacturing', 'Manufacturing'), ('greentech', 'GreenTech and Renewable Technology'), ('it', 'IT'), ('wearable', 'Wearable Tech'), ('chemical', 'Chemical'), ('bigdata', 'Big Data and Analysis'), ('social', 'Social Startups'), ('logistics', 'Logistics & Supply Chain')], max_length=20)),
                ('mentor_any_sector', models.BooleanField(default=False)),
                ('join_mentorship_portal', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='mentor_profiles/')),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
