# Generated by Django 5.2.1 on 2025-06-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0003_connectedmentor_contactprofile_faq_pastwinner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetAMentorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
