# Generated by Django 4.2.20 on 2025-06-15 22:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0004_getamentoremail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits without country code', regex='^\\d{10}$')])),
                ('stakeholder_types', models.JSONField(default=list)),
                ('other_stakeholder_type', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True)),
                ('association_interest', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('maybe', 'Maybe'), ('already_associated', 'Already Associated with Eureka! 2024')], max_length=50)),
                ('linkedin_url', models.TextField()),
                ('networking_cities', models.JSONField(default=list)),
                ('other_networking_city', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_sector_1', models.CharField(choices=[('blockchain', 'Blockchain / Deep Learning / Web3'), ('fmcg', 'FMCG'), ('saas', 'SaaS'), ('foodtech', 'FoodTech'), ('edutech', 'EduTech'), ('fintech', 'FinTech'), ('biotech', 'BioTech'), ('ecommerce', 'E-Commerce'), ('healthcare', 'Healthcare'), ('consulting', 'Consulting'), ('agriculture', 'Agriculture'), ('iot', 'IoT'), ('manufacturing', 'Manufacturing'), ('greentech', 'GreenTech and Renewable Technology'), ('it', 'IT'), ('wearable', 'Wearable Tech'), ('chemical', 'Chemical'), ('bigdata', 'Big Data and Analysis'), ('social', 'Social Startups'), ('logistics', 'Logistics & Supply Chain')], max_length=20)),
                ('preferred_sector_2', models.CharField(choices=[('blockchain', 'Blockchain / Deep Learning / Web3'), ('fmcg', 'FMCG'), ('saas', 'SaaS'), ('foodtech', 'FoodTech'), ('edutech', 'EduTech'), ('fintech', 'FinTech'), ('biotech', 'BioTech'), ('ecommerce', 'E-Commerce'), ('healthcare', 'Healthcare'), ('consulting', 'Consulting'), ('agriculture', 'Agriculture'), ('iot', 'IoT'), ('manufacturing', 'Manufacturing'), ('greentech', 'GreenTech and Renewable Technology'), ('it', 'IT'), ('wearable', 'Wearable Tech'), ('chemical', 'Chemical'), ('bigdata', 'Big Data and Analysis'), ('social', 'Social Startups'), ('logistics', 'Logistics & Supply Chain')], max_length=20)),
                ('preferred_sector_3', models.CharField(choices=[('blockchain', 'Blockchain / Deep Learning / Web3'), ('fmcg', 'FMCG'), ('saas', 'SaaS'), ('foodtech', 'FoodTech'), ('edutech', 'EduTech'), ('fintech', 'FinTech'), ('biotech', 'BioTech'), ('ecommerce', 'E-Commerce'), ('healthcare', 'Healthcare'), ('consulting', 'Consulting'), ('agriculture', 'Agriculture'), ('iot', 'IoT'), ('manufacturing', 'Manufacturing'), ('greentech', 'GreenTech and Renewable Technology'), ('it', 'IT'), ('wearable', 'Wearable Tech'), ('chemical', 'Chemical'), ('bigdata', 'Big Data and Analysis'), ('social', 'Social Startups'), ('logistics', 'Logistics & Supply Chain')], max_length=20)),
                ('mentor_any_sector', models.BooleanField(default=False)),
                ('join_mentorship_portal', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='emn/mentor_profiles/')),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MentorRegistration',
        ),
    ]
