# Generated by Django 4.2.20 on 2025-06-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0005_mentor_delete_mentorregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='otp_created_at',
        ),
    ]
