# Generated by Django 4.2.20 on 2025-06-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0006_emailotp_remove_mentor_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
