# Generated by Django 4.2.20 on 2025-08-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0009_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='password_changed',
            field=models.BooleanField(default=False),
        ),
    ]
