# Generated by Django 4.2.20 on 2025-08-18 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0011_emnuser_startup_startupbookmark_mentormatch_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='startupbookmark',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='startupbookmark',
            name='startup',
        ),
        migrations.RemoveField(
            model_name='startupbookmark',
            name='user',
        ),
        migrations.DeleteModel(
            name='MentorBookmark',
        ),
        migrations.DeleteModel(
            name='StartupBookmark',
        ),
    ]
