# Generated by Django 4.2.20 on 2025-08-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0012_alter_startupbookmark_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='calendly_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startup',
            name='calendly_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
