# Generated by Django 4.2.20 on 2025-08-22 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0014_availabilityslot_googlecalendartoken_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='calendly_link',
        ),
        migrations.RemoveField(
            model_name='startup',
            name='calendly_link',
        ),
    ]
