# Generated by Django 4.2.20 on 2025-08-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0016_remove_booking_slot_booking_end_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyavailability',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='weeklyavailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weeklyavailability',
            name='availability_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='weeklyavailability',
            name='slot_duration',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='weeklyavailability',
            name='startup',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_availability', to='emn.startup'),
        ),
        migrations.RemoveField(
            model_name='weeklyavailability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='weeklyavailability',
            name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='weeklyavailability',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='weeklyavailability',
            name='weekday',
        ),
    ]
