# Generated by Django 4.2.20 on 2025-08-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0017_alter_weeklyavailability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='accept_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='reject_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
