# Generated by Django 4.2.20 on 2025-08-23 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0018_connectionrequest_accept_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('joined', 'Joined Meeting'), ('left', 'Left Meeting'), ('clicked_link', 'Clicked Meet Link')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_tracks', to='emn.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emn.emnuser')),
            ],
        ),
    ]
