# Generated by Django 4.2.20 on 2025-08-23 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0019_meetingtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingtracker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emn.emnuser'),
        ),
    ]
