# Generated by Django 4.2.20 on 2025-08-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0020_alter_meetingtracker_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingtracker',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='meetingtracker',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='meetingtracker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='meetingtracker',
            name='user_agent',
        ),
        migrations.AlterField(
            model_name='meetingtracker',
            name='action',
            field=models.CharField(choices=[('clicked_link_mentor', 'Mentor Joined'), ('clicked_link_startup', 'Startup Joined'), ('clicked_link_unknown', 'Unknown Joined')], max_length=30),
        ),
    ]
