# Generated by Django 4.2.20 on 2025-09-06 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0022_meeting_reschedulerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('scheduled', 'Meeting Scheduled'), ('cancelled', 'Meeting Cancelled'), ('reschedule_requested', 'Reschedule Requested'), ('rescheduled', 'Meeting Rescheduled')], max_length=20)),
                ('actor_name', models.CharField(max_length=255)),
                ('actor_type', models.CharField(choices=[('mentor', 'Mentor'), ('startup', 'Startup')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='emn.meeting')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
