# Generated by Django 4.2.20 on 2025-09-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0023_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
