# Generated by Django 4.2.20 on 2025-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0025_meeting_google_event_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentormatch',
            options={'ordering': ['-match_score', '-created_at']},
        ),
        migrations.AddField(
            model_name='mentormatch',
            name='match_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mentormatch',
            name='score_factors',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='mentormatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
