# Generated by Django 4.2.20 on 2025-09-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0026_alter_mentormatch_options_mentormatch_match_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emnuser',
            name='dashboard_access',
            field=models.BooleanField(default=False),
        ),
    ]
