# Generated by Django 4.2.20 on 2025-09-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emn', '0027_emnuser_dashboard_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_profile', to='emn.emnuser'),
        ),
    ]
